name: Test & Deploy Password Manager

on:
  push:
    branches:
      - main

# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         type: string
#         default: dev
#         required: false


jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'
      - name: Install make
        run: sudo apt install make -y
      - name: Install Application Requirements
        run: make requirements
      - name: Install Dev Dependencies
        run: make dev-setup
      - name: Run Checks
        run: make run-checks